name: Build Docker Image
on: push
jobs:
  publish-docker-image:
    name: Build the docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
            docker build . --tag ghcr.io/kevineduardo/whatsapp-api-nodejs:latest
            docker push ghcr.io/kevineduardo/whatsapp-api-nodejs:latest